# Generated by Django 3.2.7 on 2021-09-16 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
        ('orders', '0002_order_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='note',
            field=models.CharField(blank=True, default=' ', max_length=110, null=True),
        ),
        migrations.RemoveField(
            model_name='order',
            name='table',
        ),
        migrations.AddField(
            model_name='order',
            name='table',
            field=models.ManyToManyField(blank=True, to='menu.Table'),
        ),
    ]
