# Generated by Django 3.2.7 on 2021-09-16 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
        ('orders', '0003_auto_20210916_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='note',
        ),
        migrations.AlterField(
            model_name='order',
            name='table',
            field=models.ManyToManyField(blank=True, default=1, null=True, to='menu.Table'),
        ),
    ]
