# Generated by Django 3.2.7 on 2021-09-17 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='max',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
