version: "3.8"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:

# docker-compose run web python manage.py makemigrations
# docker-compose run web python manage.py migrate
# docker-compose run web python manage.py createsuperuser
# docker exec -it devops_web_1 bash
