version: "3.8"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    command: >
      sh -c "python manage.py migrate &&
             python manage.py wait_for_db &&
             python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db
 
  db:
    image: postgres:13
    env_file:
      - ./.env.dev
    # volumes: 
    #   - pgdata:/var/lib/postgresql/data

  rabbitmq:
    container_name: interactive_menu_broker
    restart: always
    # command: > 
    #   sh -c "celery -A interactive_menu worker -l info"
    image: rabbitmq:latest
    ports:
      - 5673:5672
    env_file:
      - ./.env.dev
    depends_on:
      - web

  redis:
    container_name: interactive_menu_redis
    image: redis:latest
    env_file:
      - ./.env.dev
    ports:
      - 6379:6379
    depends_on:
      - web


volumes:
  pgdata:


