version: "3.8"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    command: >
      sh -c "python manage.py migrate &&
             python manage.py wait_for_db &&
             python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./.env.prod
    depends_on:
      - db
      - rabbitmq
      - redis
 
  db:
    image: postgres:13
    hostname: postgres
    env_file:
      - ./.env.prod
    volumes: 
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    container_name: interactive_menu_broker
   
    restart: on-failure
    image: rabbitmq:latest
    env_file:
      - ./.env.prod
    depends_on:
      - redis
    ports:
      - 5672:5672
      - 15672:15672 # here, we can access rabbitmq management plugin   
    hostname: rabbitmq
  redis:
    container_name: interactive_menu_redis
    image: redis:latest
    restart: on-failure
    
    hostname: redis
    env_file:
      - ./.env.prod
    ports:
      - 6379:6379
    

volumes:
  pgdata: