# Generated by Django 3.2.8 on 2021-11-25 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(blank=True, choices=[('OK', 'OK'), ('SE', 'Sem estoque')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='itemrevenue',
            name='id',
            field=models.BigAutoField(auto_created=True, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='itemstock',
            name='status',
            field=models.CharField(blank=True, choices=[('OK', 'OK'), ('SE', 'Sem estoque')], max_length=3, null=True),
        ),
    ]
