# Generated by Django 3.2.8 on 2021-12-13 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20211208_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='item',
            name='slug',
        ),
    ]
