# Generated by Django 3.2.7 on 2021-09-21 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='cpf',
            new_name='CPF',
        ),
    ]
