# Generated by Django 3.2.8 on 2021-11-18 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_config', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ('profile',), 'verbose_name': 'employe', 'verbose_name_plural': 'employes'},
        ),
    ]
